version: '2'
services:
  cron:
    build: .
    env_file:
      - account-info.env 
    links:
      - redis
    volumes_from:
      - redis
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always
volumes:  
  redis_data:
